Modal Update e Insert de Matérias
GAB-Incorporated/NavGo-FrontEnd pull request #5
Opened 2024-08-31 22:37 UTC by Drdrakin

As modais de Update e Insert de matérias. Notável que existe uma pasta em pages contendo um exemplo de como ter dois botões de abrir modal em uma página apenas. Ela é totalmente descartável e só existe para testar as modais criadas

2024-09-01 13:41 UTC, AurorinhaBoreal requested changes

2024-09-01 13:41 UTC, AurorinhaBoreal commented on src/pages/ModalSubject/index.jsx
> +    const initialSubjectName = "Matemática";
Imagino que isso aqui é pra testes não? Como o useState do UpdateSubjectBody ja tem o valor default de "", não teria necessidade de passar esses por padrão

2024-09-02 17:12 UTC, Drdrakin commented on src/pages/ModalSubject/index.jsx
> +    const initialSubjectName = "Matemática";
Sim, vou apenas deletar esse arquivo, a página não faz sentido, era só pra revisão msm

2024-09-02 20:19 UTC, AurorinhaBoreal approved these changes
Só esses index chatão mesmo ;-;

2024-09-02 22:29 UTC, brunofsilva2 approved these changes
mto bem feito e organizado!

2024-09-02 22:31 UTC, merged