modal: Create and Update locations
GAB-Incorporated/NavGo-FrontEnd pull request #8
Opened 2024-09-05 00:05 UTC by brunofsilva2

2024-09-05 01:25 UTC, Drdrakin requested changes
Pequenas coisas precisam ser mudadas quanto a receber mensagens do backend na modal, mas está legal, e pelo visto a lógica funciona de forma maneira. Mas precisa ser reescrito pois você não utilizou o corpo da modal que a Aurora criou para seguir o padrão.

Desativar o erro do eslint foi muito safado 😭😭 Mas vamos seguir sem mesmo, pois não nos beneficia isso mesmo.

2024-09-05 01:25 UTC, Drdrakin commented on eslint.config.js
> +      'react/prop-types': 'off', // remove temporariamente a validação de props
Safado, desativou o teste pra não falhar KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK

2024-09-05 01:25 UTC, Drdrakin commented on src/components/ModalBody/LocationBody/CreateLocation/index.jsx
> +            });
Aqui você retorna um toast de erro caso o Catch fisgue um erro. O backend dessa específica funcionalidade foi feito por mim, mas também todos que não foram feitos por mim retornam mensagens de erro. É importante fazer uso dessa mensagem de erro no corpo do Toast, ou seja na description. Uma lógica legal é mostrar a message do erro caso exista, e se não houver message apenas você retorna uma mensagem fixa como essa.

2024-09-05 01:25 UTC, Drdrakin commented on src/components/ModalBody/LocationBody/CreateLocation/index.jsx
> +            });
Retorne mensagens de erro diretamente do back sempre onde possível

2024-09-09 19:02 UTC, Drdrakin requested changes
Primeiro quero dizer que melhorou bastante, agora o Modal criado é de fato o do modelo, bem mais simples com certeza, mas ainda possui uma característica ruim da revisão anterior. Não vou ser chato com detalhes irrelavantes, mas na tela ainda existe Modal Dentro de Modal, o que foge do nosso design. 

Isso acontece pois você cria um botão para abrir o modal no próprio body do modal, ou seja, esse botão faz com que o conteúdo só seja gerado após você apertar nele.

Na prática, desse jeito seria assim: Adm abre o painel administrativo e clica no botão que vai estar entitulado "Criar curso", aí depois disso vai abrir um modal inteiro com outro botão escrito "Criar Curso" novamente, entende que é uma falha de design? A mudança é simples, seria retirar a lógica que faz com que outro modal seja gerado ao clicar no botão e remover o botão, fazendo com que o conteúdo esteja todo em um só modal.

2024-09-09 19:05 UTC, Drdrakin commented
Outra coisa, bem pequena mas como precisa fazer mudança não vai custar muito: o botão de cadastrar é centralizado, as labels dos inputs estão azuis, preto é o padrão

2024-09-11 01:55 UTC, brunofsilva2 commented
Finalizei a criação desse modal, o Gui viu a parte visual e estava tudo correto, desde as api's de local-type até a de buildings. O modal está com o formato correto agora, como o Gui me mostrou. 
Só aguardando o review de vocês para poder mergear na dev.

2024-09-11 23:12 UTC, Drdrakin reviewed
Ficou bom! Funciona bonitinho, talvez precise abrir uma breve PR quando for fazer o back de buildings tbm!

2024-09-11 23:13 UTC, merged